# Generated by Django 3.2 on 2023-04-11 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dbins", "0003_posts_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posts",
            name="user_id",
        ),
    ]
